# Generated by Django 4.0.4 on 2022-05-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='main_doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.maindoctor'),
        ),
    ]
