# Generated by Django 4.0.4 on 2022-05-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_hospital_main_doctor_maindoctor_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindoctor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='main_doctor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.maindoctor'),
            preserve_default=False,
        ),
    ]
