# Generated by Django 4.0.4 on 2022-05-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_maindoctor_hospital_hospital_main_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendingdoctor',
            name='hospital_connect',
        ),
        migrations.RemoveField(
            model_name='attendingdoctor',
            name='nurse_connect',
        ),
        migrations.RemoveField(
            model_name='attendingdoctor',
            name='patient_connect',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='main_doctor',
        ),
        migrations.RemoveField(
            model_name='maindoctor',
            name='doctors_cnnct',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='hospital_connect',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital_connect',
        ),
    ]
