# Generated by Django 4.0.4 on 2022-05-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_attendingdoctor_hospital_connect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hospital_connect',
        ),
    ]
