# Generated by Django 4.0.4 on 2022-05-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_patient_hospital_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendingdoctor',
            name='hospital_connect',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='hospital_connect',
        ),
    ]
