# Generated by Django 4.0.4 on 2022-05-22 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_attendingdoctor_hospital_connect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindoctor',
            name='hospital_connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.hospital', verbose_name='Больница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='nurse_connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.nurse', verbose_name='мед.сестры'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='patient_connect',
        ),
        migrations.AddField(
            model_name='nurse',
            name='patient_connect',
            field=models.ManyToManyField(to='app.patient', verbose_name='Пациенты'),
        ),
    ]
