# Generated by Django 4.0.4 on 2022-05-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_maindoctor_hospital_connect_maindoctor_nurse_connect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendingdoctor',
            name='nurse_connect',
        ),
        migrations.RemoveField(
            model_name='attendingdoctor',
            name='patient_connect',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='main_doctor',
        ),
        migrations.RemoveField(
            model_name='maindoctor',
            name='doctors_cnnct',
        ),
        migrations.RemoveField(
            model_name='maindoctor',
            name='hospital_connect',
        ),
        migrations.RemoveField(
            model_name='maindoctor',
            name='nurse_connect',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='patient_connect',
        ),
    ]
