# Generated by Django 4.0.4 on 2022-05-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_attendingdoctor_nurse_connect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendingdoctor',
            name='hospital_connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.hospital', verbose_name='Больница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendingdoctor',
            name='nurse_connect',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.nurse', verbose_name='Мед-сестры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendingdoctor',
            name='patient_connect',
            field=models.ManyToManyField(to='app.patient', verbose_name='Пациенты'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='main_doctor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.maindoctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='doctors_cnnct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.attendingdoctor', verbose_name='Доктора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='nurse_connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.nurse', verbose_name='мед.сестры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='patient_connect',
            field=models.ManyToManyField(to='app.patient', verbose_name='Пациенты'),
        ),
    ]
