# Generated by Django 4.0.4 on 2022-05-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_attendingdoctor_hospital_connect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendingdoctor',
            name='hospital_connect',
        ),
        migrations.RemoveField(
            model_name='maindoctor',
            name='nurse_connect',
        ),
    ]
