# Generated by Django 4.0.4 on 2022-05-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_attendingdoctor_hospital_connect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='patient_connect',
        ),
    ]
