# Generated by Django 4.0.4 on 2022-05-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_attendingdoctor_hospital_maindoctor_nurse_connect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendingdoctor',
            name='hospital',
        ),
    ]
